### ISSUE TITLE
vip import files: cannot import files containing spaces

### ISSUE THREAD

**Issue by david-binda** [Automattic/vip-cli#103]
When importing files with spaces in file names, the following error is being thrown:

```
_http_client.js:50
    throw new TypeError('Request path contains unescaped characters.');
    ^

TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:50:11)
    at Object.exports.request (http.js:31:10)
    at /home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/import.js:14:18
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

Looks like we are not properly urlencoding path in https://github.com/Automattic/vip-cli/blob/master/src/lib/import.js#L10

**Comment by joshbetz** [comment]
Per #106 I think this is expected behavior.
