### ISSUE TITLE
Error connecting to https://api.wpvip.com/graphql after data sync

### ISSUE THREAD

**Issue by petervibert** [Automattic/vip-cli#111]
I completed a successful data sync using `vip sync --app XX --env develop`. I watched it (mostly) while it worked and saw no errors, all the checkmarks showed up, and it said it was successful. When I went back to my terminal a few minutes later, there were lots of the following:

```
 ✕  Unexpected error: Please contact VIP Support with the following error:
  Error: Network error: request to https://api.wpvip.com/graphql failed, reason: connect ECONNREFUSED 192.0.66.2:443
    at new ApolloError (/usr/local/lib/node_modules/@automattic/vip/node_modules/apollo-client/bundle.umd.js:121:32)
    at /usr/local/lib/node_modules/@automattic/vip/node_modules/apollo-client/bundle.umd.js:1188:45
    at /usr/local/lib/node_modules/@automattic/vip/node_modules/apollo-client/bundle.umd.js:1619:21
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@automattic/vip/node_modules/apollo-client/bundle.umd.js:1618:22
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/usr/local/lib/node_modules/@automattic/vip/node_modules/apollo-client/bundle.umd.js:1613:26)
    at /usr/local/lib/node_modules/@automattic/vip/node_modules/apollo-client/bundle.umd.js:1115:35
    at process._tickCallback (internal/process/next_tick.js:178:7)

```
This doesn't look concerning and @scottsweb mentioned this could be due to the SSH session expiring. Logging here anyway just in case.

**Comment by joshbetz** [comment]
@petervibert Do you remember if your computer was sleeping or the network otherwise disconnected during the sync?

**Comment by joshbetz** [comment]
I'm thinking this is a duplicate of #44
