### ISSUE TITLE
app commands (even help) throwing an error

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#130]
Running `app` commands gives me a `ENOENT` error:

``` shell
SWTBMBP:Desktop simonwheatley$ vip --version
1.0.0-dev-build13
SWTBMBP:Desktop simonwheatley$ vip

  Usage: vip [options] [command]

  Commands:

    app     List and modify your VIP Go apps
    help    Display help
    logout  Logout from your current session
    sync    Sync production to a development environment

  Options:

    -h, --help     Output usage information
    -v, --version  Output the version number

SWTBMBP:Desktop simonwheatley$ vip app --help

  ✕  Unexpected error: Please contact VIP Support with the following error:
  Error: spawn vip-app ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
SWTBMBP:Desktop simonwheatley$ vip app list

  ✕  Unexpected error: Please contact VIP Support with the following error:
  Error: spawn vip-app ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

I've tried logging out and back in again.

**Comment by joshbetz** [comment]
Can you run `npm i -g @automattic/vip` and try again?

**Comment by chrean** [comment]
Running `1.0.0-dev-build13`, could not reproduce the error.

**Comment by joshbetz** [comment]
Related: https://github.com/leo/args/issues/69

We're doing it the "right" way though, so I think something else must be going on for you.

**Comment by simonwheatley** [comment]
This was related to an NPM installation error, and was resolved by reinstalling Node.
