### ISSUE TITLE
Quitting the display of an app list shows an error

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#175]
Steps to reproduce:

1. `vip app list`
2. Type `q`

An error is displayed:

```
 ✕  Unexpected error: Please contact VIP Support with the following error:
  Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
```

**Comment by elazzabi** [comment]
It looks like a race condition where the parent process quits before the child. Then the child can't write the status on the stdout of the parent because it's already closed => that `EPIPE` error.

Will debug more...

**Comment by rumoradvertising** [comment]
This is my output from running the command "vip app list" I was told that leaving the error message here would help to fix it.

  ✕  Unexpected error: Please contact VIP Support with the following error:
  Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:717:5)
    at Socket._write (net.js:729:8)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at PassThrough.ondata (_stream_readable.js:666:20)
    at PassThrough.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)

Edit: 
Windows 10 version 1803 build 17134.471
Node version 10.14.2
npm version 6.5.0
vip version 1.2.1

**Comment by BrookeDot** [comment]
I'm not sure if @rumoradvertising's results are related to Simon's report of failure on keyboard input. We've been discussing the issue regarding `vip app list` and the error RUMOR is receiving  in 86052-zd-wordpressvip

**Comment by elazzabi** [comment]
Hello, thanks for reporting this.

Yes the two errors are related and this bug is scheduled to be resolved in the next patch/minor release 🙌
