### ISSUE TITLE
Crash when trying to import db and search-replace on WPCOM Imports Sandbox

### ISSUE THREAD

**Issue by emrikol** [Automattic/vip-cli#295]
Error message:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn go-search-replace ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Command ran: `sudo -u wpdev /home/wpcom/.node/bin/vip import db migration-test-02.go-vip.co /tmp/migrate-15797879/dump_of_blog_15797879_created_1520612432.sql.gz --skip-confirm --search-replace viptest.wordpress.com,migration-test-02.go-vip.co --search-replace viptest.files.wordpress.com/,migration-test-02.go-vip.co/wp-content/uploads/ --search-replace /home/wpcom/public_html/wp-content/blogs.dir/04e/15797879/files/20,20`

If I run the command from an interactive shell as the `wpdev` user, it doesn't crash but seems to stick (or it's taking a very long time):

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Importing SQL for site:
-- Site: migration-test-02.go-vip.co (#787)
-- Environment: develop
-- Search Replace: viptest.wordpress.com -> migration-test-02.go-vip.co
-- Search Replace: viptest.files.wordpress.com/ -> migration-test-02.go-vip.co/wp-content/uploads/
-- Search Replace: /home/wpcom/public_html/wp-content/blogs.dir/04e/15797879/files/20 -> 20
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Are you sure? (y/n) y
Invalid from URL
```

**Comment by joshbetz** [comment]
Sounds like it's because the search-replace command is not in the current user's PATH.

**Comment by trepmal** [comment]
Just noting that yesterday I did an import from the imports sandbox

1. ssh'd to the sandbox
2. `sudo -i -u wpdev`
3. (exported db, 7G)
3. ran `vip import db techcrunch-com.go-vip.co techcrunch-com.go-vip.co.sql --search-replace techcrunch-com.go-vip.co,techcrunch.com`
4. finished in around 30 minutes

Didn't crash or anything, but did have a slow start when I got logged out of VIP CLI between export and reimport

**Comment by joshbetz** [comment]
> Didn't crash or anything, but did have a slow start when I got logged out of VIP CLI between export and reimport

This should be fixed since https://github.com/Automattic/vip-cli/pull/292 which was shipped with the newest version yesterday.
