### ISSUE TITLE
Issues reported installing on VVV

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#301]
I pointed our client at https://vip.wordpress.com/documentation/vip-go/vip-cli/#fixing-npmnode-permissions

They ran:

```
sudo chown vagrant:vagrant bin
```

Then ran:

```
npm install -g @automattic/vip@next
/usr/bin/vip -> /usr/lib/node_modules/@automattic/vip/dist/bin/vip.js
/usr/bin/vip-app -> /usr/lib/node_modules/@automattic/vip/dist/bin/vip-app.js
/usr/bin/vip-app-list -> /usr/lib/node_modules/@automattic/vip/dist/bin/vip-app-list.js
/usr/bin/vip-sync -> /usr/lib/node_modules/@automattic/vip/dist/bin/vip-sync.js
/usr/bin/vip-wp -> /usr/lib/node_modules/@automattic/vip/dist/bin/vip-wp.js

> keytar@4.4.1 install /usr/lib/node_modules/@automattic/vip/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install WARN install libsecret-1.so.0: cannot open shared object file: No such file or directory
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 3.13.0-164-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/@automattic/vip/node_modules/keytar
gyp ERR! node -v v10.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> @automattic/vip@1.4.0-dev5 postinstall /usr/lib/node_modules/@automattic/vip
> node ./helpers/check-version.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@4.4.1 (node_modules/@automattic/vip/node_modules/keytar):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@4.4.1 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @automattic/vip@1.4.0-dev5
added 178 packages from 115 contributors in 5.682s
```

**Comment by mjangda** [comment]
Looks like the install itself worked fine; the optional keytar package just failed but it's not critical to using VIP-CLI.
