### ISSUE TITLE
toLowerCase issue with app picker

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#302]
```
SWTBMBP:vip-cli simonwheatley$ vip sync
✔ Which app? · REDACTEDAPPWITHCHILDENVIRONMENT

  ✕  Unexpected error: Please contact VIP Support with the following error:
  TypeError: Cannot read property 'toLowerCase' of undefined
    at formatEnvironment (/Users/simonwheatley/A8c/vip-cli/dist/lib/cli/format.js:37:36)
    at keyValue (/Users/simonwheatley/A8c/vip-cli/dist/lib/cli/format.js:99:13)
    at confirm (/Users/simonwheatley/A8c/vip-cli/dist/lib/cli/prompt.js:20:36)
    at Args._args.default.argv (/Users/simonwheatley/A8c/vip-cli/dist/lib/cli/command.js:334:43)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by nickdaugherty** [comment]
It looks like this happens when a site has exactly 1 non-production environment.
