### ISSUE TITLE
Can't stop a sandbox

### ISSUE THREAD

**Issue by trepmal** [Automattic/vip-cli#303]
```
$ npm -v
5.5.1
$ vipgo -V
0.21.2
$ vipgo sandbox stop chryslercapital.go-vip.co
{ Error: ENOENT: no such file or directory, open '/home/vipdev/.vip-cli/sandbox'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.get (/home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/config.js:17:13)
    at Object.stop (/home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/sandbox.js:199:9)
    at /home/vipdev/.node/lib/node_modules/wpvip-cli/build/bin/vipgo-sandbox.js:75:13
    at Object.maybeConfirm (/home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/utils.js:213:2)
    at /home/vipdev/.node/lib/node_modules/wpvip-cli/build/bin/vipgo-sandbox.js:70:10
    at /home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/sandbox.js:279:10
    at Request.callback (/home/vipdev/.node/lib/node_modules/wpvip-cli/node_modules/vip/node_modules/superagent/lib/node/index.js:785:12)
    at Request.request.callback (/home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/api.js:41:12)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/vipdev/.vip-cli/sandbox' }
```

Rolled back to v 0.20.0 and still having problems

```
$ vip -V
0.20.0
$ vip sandbox stop 794
{ Error: ENOENT: no such file or directory, open '/home/vipdev/.vip-cli/sandbox'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.get (/home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/config.js:17:13)
    at Object.stop (/home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/sandbox.js:199:9)
    at /home/vipdev/.node/lib/node_modules/wpvip-cli/build/bin/vip-sandbox.js:75:13
    at Object.maybeConfirm (/home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/utils.js:225:2)
    at /home/vipdev/.node/lib/node_modules/wpvip-cli/build/bin/vip-sandbox.js:70:10
    at /home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/sandbox.js:279:10
    at Request.callback (/home/vipdev/.node/lib/node_modules/wpvip-cli/node_modules/vip/node_modules/superagent/lib/node/index.js:785:12)
    at Request.request.callback (/home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/api.js:41:12)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/vipdev/.vip-cli/sandbox' }
```

I pretty much expect this to be user error :/

I can list my sandboxes (which confirms that the attempt to `stop` is failing).

**Comment by joshbetz** [comment]
@mjangda we may want to reconsider never doing cleanup. The relative cost (a few KB) doesn't seem worth continually running into this. Especially if it's going to be internal-only now.

**Comment by joshbetz** [comment]
It also forces you to interact with the upgrade process in a way that you wouldn't have to otherwise. Every single time an upgrade runs, you have to answer `Do you want to delete the VIP CLI configuration? [n]`.

**Comment by trepmal** [comment]
> Do you remember if you saw this message and what your response was?

Initially I answered `n`.

I upgraded again. (`npm i -g wpvip-cli`)
Answered `y` to _Do you want to delete the VIP CLI configuration?_
Re-logged in.
Still can't stop :(

**Comment by trepmal** [comment]
Do I need to do something special? I'm still having issues

**Comment by joshbetz** [comment]
I stopped the container for you. This should be fixed when we release the next version. Let us know if you continue to run into problems and we can prioritize a new release.
