### ISSUE TITLE
WP CLI: Cancelling command in Windows displays error (but command is cancelled)

### ISSUE THREAD

**Issue by dchymko** [Automattic/vip-cli#436]
## Description
When cancelling a running WP CLI command on Windows, the following error is displayed:
```
  ✕  Unexpected error: Please contact VIP Support with the following error:
  TypeError: Cannot read property 'setRawMode' of null
    at ReadStream.setRawMode (tty.js:66:28)
    at Interface._setRawMode (readline.js:251:16)
    at Interface.close (readline.js:376:10)
    at IOStream.commandStreams.stdoutStream.on (C:\Users\User\Desktop\cli\vip\dist\bin\vip-wp.js:305:20)
    at IOStream.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

The command is still cancelled on the runner, but this is not clear to the user based on the terminal ouput

**Comment by joshbetz** [comment]
Related: #361

**Comment by dchymko** [comment]
Could be related:
https://github.com/SBoudrias/Inquirer.js/issues/565

(The `Enquirer` package uses `Inquirer` 6.2.2)
