### ISSUE TITLE
Cannot delete property '0' of [object Array]

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-cli#83]
I can't easily reproduce this now (I think I was in a non-Go git repo), but flagging for investigation:

```
$ vip sync

  ✕  Please contact VIP Support with the following error:
  TypeError: Cannot delete property '0' of [object Array]
    at Array.pop (<anonymous>)
    at Args._args2.default.argv (~/.nvm/versions/node/v8.9.4/lib/node_modules/@automattic/vip/dist/lib/cli/command.js:214:42)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by mjangda** [comment]
Closing; can't reproduce anymore. I was using a pretty old version so maybe fixed or gremlins.
